title: Shark's Blog
author: CalebEngel
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Check back frequently for some Shark updates.

# social links
twitter_username: socialmedia_sucks # DO NOT include the @ character, or else the build will fail!
github_username:  CalebEngel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
